### ISSUE TITLE
isort ordering issues with python-future

### ISSUE THREAD

**Issue by mmphego** [timothycrosley/isort#1005]
Hi,

We are currently doing the `Python2to3` migration using `futurize` which adds the [future.standard_library](https://python-future.org/reference.html?highlight=standard_library#module-future.standard_library). According to the docs the `standard_library` should be added after `__future__` but before any other imports. 

Below you will find current `isort` configuration and source code snippets **before and after** isort.

What I want is to have `future` import and `standard_library` below `__future__`, but `isort` doesn't like that as `future` is a 3rd party package.

## What I have before running isort
```python
from __future__ import absolute_import

from future import standard_library

standard_library.install_aliases()  

import os
import re
import time

from logging.handlers import SysLogHandler

from builtins import len, object, str

from katlogger import log_formatter, log_rollover

from .query_elastic import QueryElastic

```

## What I have after running isort
```python
from __future__ import absolute_import

# Python Standard Library
import os
import re
import time

from builtins import len, object, str
from logging.handlers import SysLogHandler

# Third Library
from future import standard_library

# Explicitly Local
from .query_elastic import QueryElastic

# CAM Packages
from katlogger import log_formatter, log_rollover

standard_library.install_aliases()  # noqa: E402
```

## What I want after isort
```python
from __future__ import absolute_import

from future import standard_library
standard_library.install_aliases() 

# Python Standard Library
import os
import re
import time

from builtins import len, object, str
from logging.handlers import SysLogHandler

# Explicitly Local
from .query_elastic import QueryElastic

# CAM Packages
from katlogger import log_formatter, log_rollover
```

## Configuration
```toml
[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
indent = 4
line_length = 90
multi_line_output = 3
# Having imports glued together is physically painful. ;)
lines_between_types = 1
# Imports sections
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
# Imports heading
import_heading_stdlib = 'Python Standard Library'
import_heading_thirdparty = 'Third Library'
import_heading_firstparty = 'CAM Packages'
import_heading_localfolder = 'Explicitly Local'

# A list of known imports that will be forced to display within their specified category.
known_first_party = ['katlogger']
```
