### ISSUE TITLE
isort and pre-commit - not only Python files are processed

### ISSUE THREAD

**Issue by jugmac00** [timothycrosley/isort#1154]
I was using pre-commit (as in pre-commit.com) as follows:
```
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21 
    hooks:
      - id: isort
        args: [--filter-files]
```
This worked perfectly.

Once I updated to 4.3.21-2, not only Python files, but also json, rst, po, mako, html, pot and cfg files were touched and modified by isort.

In the https://github.com/timothycrosley/isort/blob/develop/CHANGELOG.md I could not find an entry for 4.3.21-2 at all.

My current workaround is following config:
```
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    - id: isort
      args: [--filter-files]
      files: \.py$
```

I am pretty new to both `pre-commit` and `isort` - so maybe I miss something.

Maybe I miss the point, but why would I want to use `isort` on a json or a po (translation) file?

P.S.: @asottile`s pre-commit`s version is 2.0.1.
