### ISSUE TITLE
namespace package sorts differently when using the `from namespace import x` form

### ISSUE THREAD

**Issue by pganssle** [timothycrosley/isort#1208]
Given a configuration file like this:

```toml
[tool.isort]
import_heading_firstparty="First party"
import_heading_thirdparty="Third party"
known_first_party = ["namespace.mymodule"]
default_section = "THIRDPARTY"
```

And an input file like this:

```python
import namespace.mymodule
from namespace import mymodule
```

Installing `isort[pyproject]` (`==4.3.21`), I get:

```
# Third party
from namespace import mymodule

# First party
import namespace.mymodule
```

Normally this would not be a problem because you can put `"namespace"` into `known_first_party`, but when the namespace is `backports` or some other shared namespace, there are both first- and third-party packages in there. It seems to me that in the case of `from x import y`, the sorting should be based on `x.y`, not on `x`.
