### ISSUE TITLE
Line length in pyproject.toml doesn't override global .isort.cfg

### ISSUE THREAD

**Issue by meshy** [timothycrosley/isort#1237]
I have been working on a project which  includes the following settings in `pyproject.toml`:

```toml
[tool.isort]
line_length = 120
```

I have found that my global `~/.isort.cfg` is overriding this setting.

```toml
[settings]
line_length = 88
```

I would have expected the project to override the global setting. I wonder if this is related to https://github.com/timothycrosley/isort/issues/1185, though it doesn't appear to be exactly the same case.
