### ISSUE TITLE
Different behavior between CLI and pre-commit hook

### ISSUE THREAD

**Issue by mighelone** [timothycrosley/isort#1245]
This is my configuration `.isort.cfg`
```
[settings]
line_length=100
multi_line_output=3
include_trailing_comma=True
```
when I run `pre-commit run --all-files`
my modules look like this
```
import os

import pandas as pd
import mylib
```
no space is added from my local lib and third party ones.

If I run from command line `isort -rc .`, the file is changed to:

```
import os

import pandas as pd

import mylib
```
adding a space between third-party and local modules.

Any idea how to get a consistent behavior?

**Comment by mighelone** [comment]
I fixed the problem using seed-isort-config before running isort in pre-commit:

```
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
  
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
```
