### ISSUE TITLE
config: Missing correspondence silently fails? `sections = ["{WROTE_AB}", ...]` and `known_{meant_abc}`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [timothycrosley/isort#1331]
Would it be possible to have `isort` complain if `sections` is defined without a corresponding `known_{snake_case}` definition? -- or conversely, if `known_{snake_case}` is defined, but is not used in `sections`?

I just spent some time chasing down an issue where section correspondence didn't exist, but it silently failed.

In my specific cast, I had the following TOML config portion:
```toml
[tool.isort]
# ...
# [ Sections ]
# See: https://github.com/timothycrosley/isort#custom-sections-and-ordering
# This determines the ordering of imports.
sections = [
    # {builtin}
    "FUTURE",
    # {builtin} + extra_standard_library
    "STDLIB",
    # known_third_party
    "THIRDPARTY",
    # known_robotlocomotion_upstream
    "ROBOTLOOMOTION_UPSTREAM",
    # known_first_party
    "FIRSTPARTY",
    # {builtin}
    "LOCALFOLDER",
]
# TODO(eric.cousineau): Rename to LCM ecosystem?
known_robotlocomotion_upstream = [
    "bot_core",
]
default_section = "THIRDPARTY"
```

But `isort==5.1.3` was formatting the following file:
```py
import time

import numpy as np

import bot_core
```
into this:
```py
import time

import bot_core
import numpy as np
```
which was not what I wanted.

In the end, it was because I misspelled `"ROBOTLOOMOTION_UPSTREAM"` - it was missing the `C` :facepalm:
